### PR TITLE
Feature/citrix adc rewrite policy

### PR DESCRIPTION
**Pull request by matt6697**
- Added citrix_adc_rewrite_action ansible module
  - Added first citrix_adc_rewrite_action ansible module integration tests
  - Removed state parameter in include:testbed.yaml statements as it seems to have been deprecated by ansible.
  - Added python CI workflow with pylint error checking of Citrix ADC and Citrix ADM modules
  - Added missing success_status in citrix_adc_nitro_request count() 
  - Modified scrape.py and compile.py scriptsto match with new nitro api reference website layout
  - Updated requirements.test.txt to match current project name (renamed netscaler-ansible-modules to citrix-adc-ansible-modules)

### CODE REVIEW

**Comment by matt6697** [comment]
I used the `pip install nitrosdk-python` to install the NITRO Python SDK which I can't find anymore on the Citrix website download area.

I had to import `ansible.module_utils.network.netscaler.netscaler` instead of the `ansible.module_utils.network.citrix_adc.citrix_adc` to make the module work and I have the following errors in pylint :

```
************* Module ansible-modules.citrix_adc_gslb_service
E:271, 0: No name 'citrix_adc' in module 'ansible.module_utils.network' (no-name-in-module)
E:271, 0: Unable to import 'ansible.module_utils.network.citrix_adc.citrix_adc' (import-error)
************* Module ansible-modules.citrix_adc_gslb_site
E:190, 0: No name 'citrix_adc' in module 'ansible.module_utils.network' (no-name-in-module)
E:190, 0: Unable to import 'ansible.module_utils.network.citrix_adc.citrix_adc' (import-error)
************* Module ansible-modules.citrix_adc_gslb_vserver
E:370, 0: No name 'citrix_adc' in module 'ansible.module_utils.network' (no-name-in-module)
E:370, 0: Unable to import 'ansible.module_utils.network.citrix_adc.citrix_adc' (import-error)
************* Module ansible-modules.citrix_adc_lb_monitor
E:807, 0: No name 'citrix_adc' in module 'ansible.module_utils.network' (no-name-in-module)
E:807, 0: Unable to import 'ansible.module_utils.network.citrix_adc.citrix_adc' (import-error)
````


Where can I download the NITRO Python SDK containing the ansible.module_utils.network.citrix_adc.citrix_adc resource ?

**Comment by matt6697** [comment]
Missing `ansible.module_utils.network.citrix_adc.citrix_adc` issue has been resolved by using the last ìnstall.py` b2cf0a3d5b63c1eb1e4dc312d0d0c359f23186c5 patch.

**Comment by matt6697** [comment]
Hi @giorgos-nikolopoulos , could you have a look on this PR and tell me if everything is ok or I need to make some changes ?

**Comment by giorgos-nikolopoulos** [comment]
We are currently reviewing our contributors license agreement.

Once this is cleared up I will let you know.

**Comment by giorgos-nikolopoulos** [comment]
After consulting with the legal department we were instructed not to accept PRs for the time being.

So this PR will not be accepted any time soon.

**Comment by matt6697** [comment]
What is the legal issue with contributing to citrix open source products ? Is it a code property issue ? A product support issue ? A citrix ADC licensing issue ? (I don't want any property on the contributed code, I just want to share the features I need for a project to the whole Citrix ADC community)

**Comment by chiradeep** [comment]
> What is the legal issue with contributing to citrix open source products ? Is it a code property issue ? A product support issue ? A citrix ADC licensing issue ? (I don't want any property on the contributed code, I just want to share the features I need for a project to the whole Citrix ADC community)

There is a larger review going on about all GitHub-related activities and we have been asked to not accept contributions until the review is completed. We will try and code up this feature on our own in the meantime.

**Pull request closed without merging**
